window.TOUR_MANIFEST = [
	{ "id": "entry-app", "title": "Entry Tour", "description": "Self-rendered tour app focused on immediate relevance.", "path": "entry/index.html", "audience": ["personal"], "default": true },
	{ "id": "neverland-parents", "title": "Neverland Parents: Escape Child-Rearing Burden", "description": "From $750k isolated burden to privileged community investment with 7-21x return through AR fantasy Springs.", "path": "history-entry/neverland-parents/tour.js", "audience": ["parents", "expecting-parents", "altruist", "homeschoolers"], "type": "history" },
	{ "id": "gov-law", "title": "Government & Law Entry", "description": "Legitimacy, accountability, and sovereignty mechanisms.", "path": "gov-law.js" },
	{ "id": "economists", "title": "Economists Entry", "description": "Markets, value discovery, NSS incentives.", "path": "economists.js" },
	{ "id": "hard-worker", "title": "Hard-Working Entry", "description": "Respect for builders, stop the drain, choose paths.", "path": "hard-worker.js" },
	{ "id": "native-launch", "title": "Native Launcher Tour (PoC)", "description": "Demonstrates opening a custom protocol (e.g., steam://, myapp://).", "path": "native-launch/index.html" },
	{ "id": "christian-world", "title": "Christian World Tour", "description": "For Christians seeking to preserve denominational diversity (Catholic, Orthodox, Protestant, etc.) through Triadization rather than forced ecumenism or schism.", "path": "history-entry/christian-world/tour.js", "audience": ["christian", "catholic", "orthodox", "protestant"], "type": "history" },
	{ "id": "roman-catholic-sea", "title": "Roman Catholic Sea Tour", "description": "For Roman Catholics specifically, showing how Triadization preserves Catholic unity (papal authority, apostolic succession) while allowing liturgical/national diversity.", "path": "history-entry/roman-catholic-sea/tour.js", "audience": ["catholic", "traditionalist", "latin-mass"], "type": "history" },
	{ "id": "free-world", "title": "Free World Tour", "description": "For those identifying with Western democracies/liberty/rule of law, showing how Triadization IS true freedom (vs Planetary uniformity masquerading as freedom).", "path": "history-entry/free-world/tour.js", "audience": ["liberal", "libertarian", "western-values"], "type": "history" },
	{ "id": "abrahamist-world", "title": "Abrahamist World Tour", "description": "For those seeing unity across Judaism, Christianity, and Islam through shared Abrahamic heritage—how World-level coordination works despite theological incompatibility.", "path": "history-entry/abrahamist-world/tour.js", "audience": ["interfaith", "sufi", "progressive-abrahamist"], "type": "history" },
	{ "id": "islamic-golden-age", "title": "Islamic Golden Age Revival Tour", "description": "For Muslims seeking to restore Islamic civilization's glory (science, philosophy, architecture, tolerance) through Triadization—ending Sunni-Shia violence, preserving Sufi mysticism.", "path": "history-entry/islamic-golden-age/tour.js", "audience": ["muslim", "islamic-civilization", "sufi", "golden-age"], "type": "history" },
	{ "id": "sub-saharan-african", "title": "Sub-Saharan African Heritage Tour", "description": "For Black Africans seeking to preserve/resurrect 1,000+ ethnic Springs (Yoruba, Igbo, Zulu, Akan, etc.) destroyed by colonialism and forced into fake nation-states.", "path": "history-entry/sub-saharan-african/tour.js", "audience": ["african", "black-african", "ethnic-african", "pan-african"], "type": "history" },
	{ "id": "progress-oriented", "title": "Progress-Oriented Minds Tour", "description": "For those valuing science/technology/innovation, showing how Triadization ACCELERATES progress through 1,000+ competing experiments vs Planetary uniformity that stifles innovation.", "path": "history-entry/progress-oriented/tour.js", "audience": ["techno-optimist", "scientist", "entrepreneur", "rationalist"], "type": "history" },
	
	{ "id": "philosopher-humanist", "title": "Philosopher & Humanist", "description": "Begin with will, ethics, and meaning; then see civilizational emergence and practice.", "path": "philosopher-humanist.js", "audience": ["philosopher", "humanist", "ethicist"], "type": "foundational" },
	{ "id": "technical-builder", "title": "Technical Builder", "description": "Start with architecture and concrete systems, then see governance mechanics.", "path": "technical-builder.js", "audience": ["engineer", "architect", "systems-thinker"], "type": "foundational" },
	{ "id": "skeptic-pragmatist", "title": "Skeptic & Pragmatist", "description": "Show practical wins, risks, and mitigation; then why it's worth testing.", "path": "skeptic-pragmatist.js", "audience": ["skeptic", "pragmatist", "empiricist"], "type": "foundational" },
	{ "id": "policy-statesman", "title": "Policy & Statesman", "description": "Governance, legitimacy, and sovereignty mechanisms for policy makers.", "path": "policy-statesman.js", "audience": ["policy-maker", "political-theorist", "statesman"], "type": "foundational" }
,
	{ "id": "command-deep-demand", "title": "Command Deep Demand — From Diagnosis to Pilots", "description": "Synthesize the 23__ series into rails, governance, metrics, and 180-day pilots.", "path": "command-deep-demand.js", "audience": ["builder", "clinician", "researcher", "policy-maker", "funder"], "type": "foundational" },
	{ "id": "command-restoration-builder", "title": "Command Restoration: Building the Alternative", "description": "For those experiencing meaning death: see the diagnosis, the architecture, and the five pilots that prove the alternative works.", "path": "command-restoration-builder.js", "audience": ["builder", "researcher", "meaning-death", "tech-worker", "finance-worker"], "type": "foundational" },
	{ "id": "animal-rights-vegan", "title": "For Those Who Care About Animals", "description": "From animal suffering to genuine symbiosis—ending the killing while feeding humanity through natural death farming and AR-enabled communication.", "path": "animal-rights-vegan.js", "audience": ["vegan", "animal-rights", "empaths", "sanctuary-supporter"], "type": "foundational" },
	{ "id": "livestock-farmer-heart", "title": "For the Livestock Farmer With a Heart", "description": "You know something is wrong with sending them away at 6 months. There's a better way—and it's more profitable. Face what we've been doing, and choose differently.", "path": "livestock-farmer-heart.js", "audience": ["farmers", "breeders", "ranchers", "agricultural-workers"], "type": "foundational" },
	{ "id": "capitalist-animal-rescue", "title": "The Capitalist With a Heart for Animals", "description": "You have capital. You're tired of waiting. Here's how to buy slaughterhouses, convert them secretly, coordinate sterilization campaigns, and END industrial slaughter in 20 years—while making 10-50× return.", "path": "capitalist-animal-rescue.js", "audience": ["investors", "capitalists", "entrepreneurs", "impact-investors"], "type": "foundational" },
	{ "id": "busy-person-heart", "title": "For The Busy Person With A Heart", "description": "You care about animals. You're exhausted and time-restrained. Here's what you need to know in 5 minutes.", "path": "busy-person-heart.js", "audience": ["busy-professionals", "time-constrained", "empaths", "quick-overview"], "type": "foundational" },
	{ "id": "scientist-animal-welfare", "title": "For Scientists & Researchers: The Data-Driven Case", "description": "Empirical evidence for animal consciousness, financial modeling, ecological impact assessment, technical feasibility (AR communication, robotic automation, non-lethal predation), and rigorous rebuttals to objections. From neuroscience to implementation.", "path": "scientist-animal-welfare.js", "audience": ["scientists", "researchers", "academics", "rationalists", "data-driven-thinkers"], "type": "foundational" },
	{ "id": "beauty-ugliness-nature", "title": "The Beauty and Ugliness of Nature—Solving the Universe's Indifference", "description": "Nature is magnificent evolutionary achievement AND constant Holocaust from ALL the universe's processes. How we preserve the beauty while ending ALL sources of suffering—bringing existence itself under conscious management.", "path": "beauty-ugliness-nature.js", "audience": ["environmentalists", "nature-romanticizers", "biologists", "animal-lovers", "philosophers"], "type": "foundational" },
	{ "id": "protect-unborn-life", "title": "For Those Who Care About Unborn Life", "description": "The brain activity standard: Using observable science (not emotional manipulation) to protect human life from conception to birth. Stop the language deception, focus on what the organism IS, and prevent 900,000 abortions/year through protection + prevention.", "path": "protect-unborn-life.js", "audience": ["pro-life", "conservatives", "religious", "parents", "anyone-valuing-human-life"], "type": "foundational" }
];

