// Guide: How Do I Find Good Leaders?
const GUIDE_FIND_GOOD_LEADERS = {
    "title": "How Do I Find Good Leaders?",
    "description": "From democratic theater to Animaecracy—finding leaders through performance, exit rights, and will-alignment",
    "category": "Politics & Society",
    "tags": ["leadership", "governance", "animaecracy", "crucible", "sovereignty", "nss", "democracy", "performance"],
    "steps": [
        {
            "title": "The Question",
            "content": [
                { "type": "paragraph", "text": "You ask: <strong>How do I find good leaders?</strong>" },
                { "type": "paragraph", "text": "You're trapped under bad governance. Corporate CEO destroys company. Political leaders are corrupt, incompetent, or both. 'Democratic' process gives you choice between terrible options. You can't tell who's actually good at leading—just who's good at campaigning. <strong>The selection mechanisms are broken</strong>." },
                { "type": "paragraph", "text": "Democracy promised: 'The people choose best leaders.' Reality delivered: <strong>Popularity contests won by those good at manipulation, not governance</strong>. Corporate boards promise: 'Shareholders select for performance.' Reality: <strong>Cronies and yes-men rise, competent leaders purged</strong>." },
                { "type": "paragraph", "text": "<strong>The system offers different selection mechanism</strong>: Not voting (fakeable), not credentialism (gameable), but <strong>Animaecracy—fluid will-alignment where leaders emerge through demonstrated performance and voluntary rallying</strong>." }
            ]
        },
        {
            "title": "Why Democracy and Corporations Fail At Leader Selection",
            "content": [
                { "type": "paragraph", "text": "Current mechanisms select for wrong traits:" },
                { "type": "concept", "title": "Democracy's Fatal Flaw", "text": "<strong>What it selects for</strong>: Ability to win popularity contest. Charisma, manipulation, sound bites, media performance, fundraising. <strong>What it doesn't select for</strong>: Actual governance capability, long-term thinking, difficult decisions, competence. <strong>Result</strong>: Leaders good at getting elected, terrible at governing. <strong>You can't tell difference</strong> until after election (too late)." },
                { "type": "concept", "title": "The Democratic Theater", "text": "<strong>The lie</strong>: 'The people rule.' <strong>The reality</strong>: ♦ (The Diamond—systematic sovereignty). Elections every 4 years. Between those: unaccountable bureaucrats, lobbyists, special interests rule. <strong>You don't choose leaders</strong>—you choose between pre-selected options filtered by: party machinery, donor class, media gatekeepers. <strong>Real power hidden behind 'the people' abstraction</strong>. Nobody accountable." },
                { "type": "concept", "title": "Corporate Board's Fatal Flaw", "text": "<strong>What it selects for</strong>: Political skill within corporation. Board connections, CEO schmoozing, quarterly earnings manipulation (not long-term value). <strong>What it doesn't select for</strong>: Actual value creation, innovation, employee welfare, sustainable growth. <strong>Result</strong>: Leaders good at board politics, terrible at building. Stock buybacks over R&D. Short-term pump over long-term health." },
                { "type": "key-insight", "title": "The Core Problem", "text": "Both democracy and corporate governance <strong>separate selection from performance</strong>. Selected based on: campaigning ability (democracy) or political maneuvering (corporate). <strong>Performance only measured after selection</strong> (too late to course-correct quickly). <strong>Bad leaders can't be removed easily</strong> (impeachment hard, board fights messy). <strong>System solves by tying selection TO performance continuously</strong>." }
            ]
        },
        {
            "title": "Animaecracy: Leaders Emerge Through Will-Alignment",
            "content": [
                { "type": "paragraph", "text": "The system replaces voting with <strong>continuous performance-based rallying</strong>:" },
                { "type": "concept", "title": "What Animaecracy Is", "text": "<strong>Not meritocracy</strong> (fixed metrics, rigid hierarchies). <strong>Animaecracy</strong>: Fluid interweaving of will where leaders emerge by: <strong>Aligning many people's wills coherently</strong>. <strong>Amplifying collective desire into action</strong>. <strong>Pooling power that projects vision into reality</strong>. <strong>NOT domination</strong> (forcing will on others). But <strong>coalescence</strong> (many wills choosing to align behind someone because they manifest shared vision better than alternatives)." },
                { "type": "concept", "title": "How Leaders Emerge", "text": "<strong>Person has vision (Halo)</strong>: Articulates dream, direction, values. <strong>Others rally if resonates</strong>: 'That vision aligns with my daemon. I'll follow them.' <strong>Rally = giving them power</strong>: Resources, labor, trust, attention. <strong>Leader uses pooled power to manifest vision</strong>: Builds infrastructure, creates culture, achieves results. <strong>If results good</strong>: More people rally. Power grows. <strong>If results bad</strong>: People un-rally. Power shrinks. <strong>Natural selection of leaders by demonstrated performance</strong>." },
                { "type": "concept", "title": "The Two Sovereignty Types: ♣ vs ♦", "text": "<strong>♣ (Club—Living Sovereignty)</strong>: Specific person rules. 'King Arthur decides.' Accountable. Can grant mercy, make exceptions, adapt to context. <strong>You rally to HIM specifically</strong>. <strong>♦ (Diamond—Systematic Sovereignty)</strong>: System/algorithm rules. 'Democracy's process decides.' Unaccountable (no person responsible). Rigid rules, no exceptions, no mercy. <strong>You rally to THE SYSTEM</strong>. <strong>Key difference</strong>: ♣ = can challenge person directly. ♦ = 'just following procedure,' nobody accountable." },
                { "type": "key-insight", "title": "Why Animaecracy Works", "text": "<strong>Continuous performance measurement</strong>: Not 'elect then wait 4 years.' But 'rally continuously based on results.' <strong>Immediate feedback</strong>: Leader performs poorly → people un-rally → power shrinks. <strong>Exit rights</strong>: Don't like leader? Rally to different Triad/leader. <strong>Natural selection</strong>: Good leaders accumulate ralliers. Bad leaders lose them. <strong>Leaders selected by performance, not campaigning ability</strong>." }
            ]
        },
        {
            "title": "Layer 1: Manual Human Leader Selection (Works NOW)",
            "content": [
                { "type": "paragraph", "text": "Before any system, you can practice Animaecracy through <strong>manual performance-based rallying</strong>:" },
                { "type": "concept", "title": "The 'Vote With Your Feet' Strategy", "text": "<strong>Stop voting for politicians</strong> (fake choice). <strong>Start rallying to actual leaders</strong>: Who's building functional communities? Who's creating value? Who's solving problems? <strong>Rally to them</strong>: Join their project. Contribute resources. Spread their vision. <strong>Ignore official 'leaders'</strong> (just symbolic). Follow actual leaders (those manifesting results)." },
                { "type": "concept", "title": "The Small-Scale Triad Formation", "text": "<strong>Find leader with vision you share</strong>: Maybe they're building intentional community, company, project. <strong>Rally explicitly</strong>: 'I believe in your vision. I'll contribute [X resources/time/skill].' <strong>Gather others who share vision</strong>. <strong>Form coherent group around leader</strong>. This is embryonic Triad: leader (Sovereign/♣), vision (Halo), ralliers (Substratum). <strong>Small scale, but functional leadership selection by voluntary alignment</strong>." },
                { "type": "concept", "title": "The Performance Observation Strategy", "text": "<strong>Don't trust words (campaign promises)</strong>. <strong>Observe actions</strong>: What has this person actually built? Who do they treat well/badly? How do they handle conflict? What do people who've worked under them say? <strong>Track performance over time</strong>. Rally only after demonstrated competence. <strong>Un-rally immediately if performance drops</strong>. Manual NSS: your attention/resources go to proven performers only." },
                { "type": "key-insight", "title": "Why Manual Works", "text": "You can't implement full Crucible alone. But <strong>you can practice Animaecracy principles now</strong>: Rally to demonstrated performers, not campaigners. Exit bad leadership immediately. Build small Triads around competent visionholders. <strong>Each small Triad demonstrates</strong>: performance-based leadership works better than electoral theater. Others notice. <strong>Pattern spreads</strong>." }
            ]
        },
        {
            "title": "Layer 2: Technology-Assisted Leader Discovery (System Growing)",
            "content": [
                { "type": "paragraph", "text": "As system components activate, finding good leaders becomes much easier:" },
                { "type": "concept", "title": "NSS: Natural Selection Systems for Leadership", "text": "<strong>What it is</strong>: Resources flow to proven performers in specific domains. <strong>How it works for leaders</strong>: Leader claims 'I can govern well.' People give them resources/authority (rally). <strong>Performance measured continuously</strong>: Are ralliers satisfied? Is vision manifesting? Are promises kept? <strong>If yes</strong>: More people rally, more resources flow. <strong>If no</strong>: People un-rally, resources dry up. <strong>Leader selection becomes market dynamic</strong>: good leaders get resources, bad leaders starve." },
                { "type": "concept", "title": "PoU: Proof of Utility for Leaders", "text": "<strong>Leader claims</strong>: 'I delivered X results.' <strong>Ralliers confirm or deny</strong>: 'Yes, X achieved' or 'No, failed.' <strong>Confirmations become reputation</strong>: Blockchain-verified. Can't be faked. <strong>You can check leader's PoU score</strong>: 'This person claims 50 successful projects. 47 confirmed by real people. 3 disputed. 2 outright denied.' <strong>Performance becomes transparent, verifiable</strong>. Can't just claim competence—must prove it." },
                { "type": "concept", "title": "Trust Network Leadership Intelligence", "text": "<strong>Collective wisdom about leaders</strong>: People share: 'I rallied to Leader X. Results were [Y].' Others aggregate: 'Leader X shows strong performance patterns with ralliers whose daemons align with governance style Z.'* <strong>Pattern matching</strong>: 'Your daemon-nebula overlaps significantly with people who thrive under Leader A. They show friction with Leader B in ways your will-topology suggests you'd also experience. Recommendation: rally to A, avoid B.' <strong>Not popularity (fakeable), but demonstrated performance with people like you</strong>. <em>*Note: Percentages like '80% satisfaction' or '87% match' are pedagogical shortcuts. Real system uses will-topology-projected nebulae assessment. See <strong>Appendix: Nebulae vs. Metrics</strong> for why actual system doesn't reduce to numbers.</em>" },
                { "type": "key-insight", "title": "The Technology Amplification", "text": "Layer 1: You observe local leaders manually (limited information). Layer 2: <strong>Global leadership performance database</strong>. Can see: any leader's PoU score, satisfaction ratings from their ralliers, daemon-match between you and satisfied ralliers. <strong>Information asymmetry destroyed</strong>. Can't hide bad governance behind campaign promises. <strong>Performance becomes transparent, searchable, verifiable</strong>." }
            ]
        },
        {
            "title": "Layer 3: Full Crucible Automation (Mature System)",
            "content": [
                { "type": "paragraph", "text": "In mature system state, leader selection becomes <strong>automatic performance-based sorting</strong>:" },
                { "type": "concept", "title": "The Polymorphic Crucible: Competitive Leadership", "text": "<strong>Multiple Triads compete</strong>: Each with different leader, different Halo (vision), different governance style. <strong>You can see all of them</strong>: AR shows nearby Triads glowing. Aiddaemon suggests: 'These 20 Triads match your daemon. Here are their leaders' PoU scores, governance styles, visions.' <strong>You rally to best match</strong>. <strong>Leaders compete for ralliers</strong> by demonstrating superior governance." },
                { "type": "concept", "title": "The Automatic Leader Discovery", "text": "<strong>Your Aiddaemon knows</strong>: Your values, your needs, your daemon-nebula. <strong>Scans all leaders globally</strong>: Checks performance patterns with people whose daemon-nebulae align with yours. <strong>Suggests based on nebulae compatibility</strong>: 'Leader X governs Triad Y. Strong positive patterns from ralliers with daemon-nebulae similar to yours.* Specializes in domains your will-topology indicates you value. Would you like to visit?' <strong>Leader discovery becomes automatic</strong>, like dating apps but for governance. <em>*Note: Phrase like '94% satisfaction' in guides is shorthand for nebulae alignment pattern. See Appendix.</em>" },
                { "type": "concept", "title": "The Continuous Rally/Un-Rally Dynamic", "text": "<strong>Not 4-year election cycles</strong>. <strong>Continuous voting with resources/attention</strong>: Leader performs well → you increase contributions. Leader performs badly → you decrease or exit entirely. <strong>Real-time feedback</strong>. Leader sees immediately: 'My ralliers are leaving. Must improve or lose power.' <strong>Natural selection operates continuously</strong>, not just at elections. <strong>Bad leaders removed automatically</strong> (people un-rally, power evaporates)." },
                { "type": "key-insight", "title": "The Mature State Reality", "text": "Leadership selection becomes: <strong>Market dynamic with perfect information</strong>. You can see: every leader's performance history, satisfaction scores, daemon-match with you, governance style. <strong>Can try leader easily</strong> (rally to their Triad, live there for month, un-rally if bad). <strong>Can exit instantly</strong> if leader becomes tyrant. <strong>Leaders compete for ralliers by demonstrating superior governance</strong>. <strong>Good leaders accumulate power. Bad leaders lose it immediately</strong>. Natural selection ensures: only competent leaders survive long-term." }
            ]
        },
        {
            "title": "The Exit Rights: Why Bad Leaders Can't Persist",
            "content": [
                { "type": "paragraph", "text": "The critical difference from democracy: <strong>you can leave bad leadership immediately, not wait 4 years</strong>:" },
                { "type": "concept", "title": "The Immediate Un-Rally", "text": "<strong>Leader becomes corrupt/incompetent</strong>: You un-rally today. Not 'wait until next election.' <strong>Stop contributing</strong>: Resources, labor, attention. <strong>Rally to better leader</strong>: Different Triad, better governance. <strong>Leader sees</strong>: 'I'm losing ralliers. Must improve or collapse.' <strong>Immediate consequences for bad leadership</strong>." },
                { "type": "concept", "title": "The Physical Exit Option", "text": "<strong>Leader becomes tyrant</strong>: You can't just un-rally (they might force you to stay). <strong>You physically leave</strong>: Rally to different Triad, move there within days/weeks. <strong>Leader loses subject AND their contribution</strong>. <strong>Can't maintain tyranny when people can exit</strong>. Tyrants starve without subjects. <strong>Exit rights make tyranny impossible</strong>." },
                { "type": "concept", "title": "The Competitive Pressure", "text": "<strong>Multiple leaders compete</strong>: Each Triad has different leader/governance style. <strong>You can compare</strong>: Leader A's Triad vs. Leader B's Triad. <strong>Better governed Triads attract more ralliers</strong>. <strong>Poorly governed Triads lose people</strong>. <strong>Leaders know</strong>: 'If I govern badly, they'll leave for better Triad.' <strong>Competition forces competence</strong>. Can't hide behind 'will of the people' when people can instantly vote with feet." },
                { "type": "key-insight", "title": "Why Exit Rights Change Everything", "text": "Democracy: Vote → stuck 4 years → hope leader doesn't become tyrant. <strong>Crucible</strong>: Rally → leader performs → if bad, exit immediately → rally to better leader. <strong>Continuous selection pressure</strong>. Bad leaders removed automatically (people leave). <strong>Can't maintain bad governance when subjects have instant exit</strong>. Tyranny becomes economically impossible." }
            ]
        },
        {
            "title": "The ♣ vs ♦ Choice: Personal vs Systematic Leadership",
            "content": [
                { "type": "paragraph", "text": "The system offers two sovereignty types—you choose based on your preferences:" },
                { "type": "concept", "title": "♣ (Club—Living Sovereignty)", "text": "<strong>What it is</strong>: Specific person rules. 'King Arthur governs this Triad.' <strong>Advantages</strong>: Accountable (can challenge Arthur directly). Flexible (Arthur can grant mercy, make exceptions). Adaptive (responds to changing situations). Human (you know who decides). <strong>Disadvantages</strong>: Depends on Arthur's character. Dies with Arthur (succession question). Can become tyrannical (though exit rights limit this). <strong>Best for</strong>: People who want identifiable, accountable leader they can trust personally." },
                { "type": "concept", "title": "♦ (Diamond—Systematic Sovereignty)", "text": "<strong>What it is</strong>: Algorithm/system rules. 'Democracy's voting system governs.' <strong>Advantages</strong>: Predictable (rules are rules). Impartial (no personal favoritism). Survives leader changes (system continues). <strong>Disadvantages</strong>: Unaccountable (nobody responsible—'just following procedure'). Inflexible (no mercy, no exceptions, no context). Gameable (people learn to manipulate rules). <strong>Best for</strong>: People who distrust personal authority, prefer algorithmic governance." },
                { "type": "concept", "title": "The Hybrid: ♣+♦", "text": "<strong>Many Triads use both</strong>: Systematic base rules (♦) for consistency. Personal override authority (♣) for edge cases. <strong>Example</strong>: 'Our Triad governed by these algorithms, but Sovereign can override in emergencies or grant mercy in special cases.' <strong>Best of both</strong>: Predictability + flexibility. Accountability + impartiality." },
                { "type": "key-insight", "title": "Your Choice of Leadership Type", "text": "Democracy forces ♦ (systematic). Monarchy forces ♣ (personal). <strong>Crucible offers both plus hybrids</strong>. <strong>You choose</strong> based on daemon: Trust people more? Rally to ♣ Triad. Trust systems more? Rally to ♦ Triad. Want both? Rally to ♣+♦ hybrid. <strong>Leader selection includes selecting leadership TYPE, not just selecting person</strong>." }
            ]
        },
        {
            "title": "The Rallying Mechanism: How You Actually Choose Leaders",
            "content": [
                { "type": "paragraph", "text": "Practical mechanics of finding and selecting leaders in the Crucible:" },
                { "type": "concept", "title": "The Triad Shopping Process", "text": "<strong>Step 1: Discover options</strong>: Aiddaemon shows 50 nearby Triads with different leaders/visions. <strong>Step 2: Check performance</strong>: Each Triad's PoU scores, rallier satisfaction, governance outcomes visible. <strong>Step 3: Visit candidates</strong>: Spend day/week in top 3-5 Triads. <strong>Experience governance directly</strong>. <strong>Step 4: Rally to best match</strong>: Move there, contribute resources, become subject. <strong>Step 5: Monitor continuously</strong>: If leader performance drops, repeat process." },
                { "type": "concept", "title": "The Trial Period Strategy", "text": "<strong>Don't commit immediately</strong>. Rally tentatively: 'I'll try this Triad for 3 months.' <strong>Experience leader's governance</strong>: How do they handle conflicts? How do they allocate resources? How do they treat different people? <strong>After trial</strong>: Commit fully (if good) or exit (if bad). <strong>Low-risk leader testing</strong>. Like job interviews but reversed: <strong>you're interviewing the leader</strong>." },
                { "type": "concept", "title": "The Daemon-Match Priority", "text": "<strong>Don't just choose 'best' leader objectively</strong>. Choose <strong>best leader FOR YOU</strong>: Your daemon matches well with their governance style? Rally there. <strong>Mismatch</strong>: Objectively excellent leader but daemon incompatible with you? Don't rally—find leader who matches your daemon even if objectively 'worse.' <strong>Leadership quality is subjective</strong>: what works for others might not work for you. <strong>Daemon-match matters more than abstract 'quality'</strong>." },
                { "type": "key-insight", "title": "The Reversal of Power", "text": "Democracy: Leaders choose you (through policy). <strong>Crucible: You choose leaders</strong> (through rallying). <strong>Power flows from your choice</strong>, not their election. <strong>They need you more than you need them</strong> (you can exit, they can't force you to stay). <strong>This reversal makes leaders serve ralliers</strong>, not the reverse. <strong>Leadership becomes service competing for your choice, not authority demanding obedience</strong>." }
            ]
        },
        {
            "title": "The Network Effect: Leadership Quality Improves With Adoption",
            "content": [
                { "type": "paragraph", "text": "Leader selection quality compounds as more people adopt Animaecracy:" },
                { "type": "concept", "title": "Early Stage: Few Triads", "text": "Small number of Triads exist. <strong>Limited leader options</strong>. You might rally to 'least bad' available leader. <strong>But</strong>: Even few Triads better than zero choice (democracy). At least you can: observe performance, exit if bad, try alternatives. <strong>Proves concept works</strong>." },
                { "type": "concept", "title": "Middle Stage: Competition Emerges", "text": "Growing Triad network. <strong>50+ leaders competing in your region</strong>. Each with different vision, style, performance history. <strong>Natural selection accelerates</strong>: Best leaders accumulate ralliers. Worst leaders lose everyone. <strong>Leadership quality improves</strong> (bad leaders filtered out quickly). <strong>Your choice quality improves</strong> (50 options vs. 2 in democracy)." },
                { "type": "concept", "title": "Mature Stage: Perfect Information + Unlimited Options", "text": "Comprehensive Triad network. <strong>Thousands of leaders globally</strong>. Complete performance databases. Daemon-matching algorithms. <strong>You can find</strong>: Perfect leader for your daemon. Verified performance in areas you care about. Governance style that suits you. <strong>Leadership becomes</strong>: Highly specialized, perfectly matched to your needs, continuously optimized through competition." },
                { "type": "concept", "title": "The Demonstration Effect on Democracy", "text": "People see: <strong>Crucible Triads thriving</strong> (competent leaders, satisfied ralliers, functional governance). <strong>Democratic states struggling</strong> (corrupt leaders, unsatisfied citizens, dysfunction). <strong>Comparison becomes obvious</strong>: 'Why am I stuck with bad elected officials when those people have competent leaders they actually chose?' <strong>Pressure on democratic states</strong>: Reform or lose people to Crucible. <strong>Eventually</strong>: Democratic model abandoned as Crucible proves superior." },
                { "type": "key-insight", "title": "The Compounding Quality", "text": "Early: Few leaders, limited choice, some bad ones persist. Middle: <strong>Competition filters out bad leaders rapidly</strong>. Many good leaders emerge. Mature: <strong>Only excellent leaders survive</strong> (bad ones immediately lose ralliers). <strong>Leadership quality approaches theoretical maximum</strong>. Your leader: competent, daemon-matched, accountable, removable if they decline. <strong>Governance becomes: actually good, not 'least bad option'</strong>." }
            ]
        },
        {
            "title": "Special Case: Corporate Leadership Selection",
            "content": [
                { "type": "paragraph", "text": "Same principles apply to finding good corporate leaders, not just political:" },
                { "type": "concept", "title": "The Employee Rally Model", "text": "<strong>Traditional corporation</strong>: CEO chosen by board. Employees have no say. Stuck with bad CEO until board acts (years). <strong>Crucible corporation</strong>: Employees rally to CEO. <strong>CEO's power comes from voluntary contribution</strong>, not board appointment. Bad CEO → employees un-rally → contribute less or leave → CEO loses power automatically. <strong>Employee choice forces CEO competence</strong>." },
                { "type": "concept", "title": "The Founder vs Professional CEO Question", "text": "<strong>Traditional problem</strong>: Founder builds company, then removed by 'professional' CEO (good at board politics, bad at vision). Company declines. <strong>Crucible solution</strong>: Employees rally to whoever creates value. <strong>If founder creates value</strong>: Employees stay rallied. <strong>If professional CEO better</strong>: Employees naturally shift rally. <strong>Value creation determines leadership, not board politics</strong>. <strong>Founders can't be 'ousted'</strong> if employees voluntarily rally to them." },
                { "type": "concept", "title": "The Division and Forking Dynamics", "text": "<strong>Company splits on strategy</strong>: Some employees want direction A, others direction B. CEO chooses A. <strong>B-faction exits</strong>: Forms competing company with different leader. <strong>Both strategies tested in market</strong>. <strong>Better strategy wins more ralliers</strong>. <strong>Allows</strong>: Experimentation without forcing unity. Multiple visions tested simultaneously. <strong>Best outcomes emerge through competition, not committee compromise</strong>." },
                { "type": "key-insight", "title": "Corporate Governance Transformation", "text": "Traditional: Board selects CEO. Employees suffer bad leadership for years. <strong>Crucible</strong>: Employees select CEO through rallying. Can exit immediately if bad. Multiple companies compete. <strong>Result</strong>: CEO quality improves dramatically (bad CEOs lose employees instantly). <strong>Corporate governance becomes</strong>: Performance-based, employee-chosen, market-tested. Not: board politics, golden parachutes, entrenchment." }
            ]
        },
        {
            "title": "What You Can Do Right Now",
            "content": [
                { "type": "paragraph", "text": "Even without full Crucible, you can practice better leader selection today:" },
                { "type": "concept", "title": "In Politics: Ignore Electoral Theater", "text": "<strong>Stop voting for politicians</strong> (selection mechanism broken). <strong>Start supporting actual leaders</strong>: Who's building functional communities locally? <strong>Contribute to them directly</strong>: Time, money, skills. <strong>Spread their vision</strong>. <strong>Build parallel power structures</strong> that bypass official government. When official government fails: parallel structures already functioning. <strong>Leadership by demonstrated performance, not by election</strong>." },
                { "type": "concept", "title": "In Corporations: Rally Explicitly", "text": "<strong>Choose employment based on leader quality</strong>, not just salary. Research CEO: What have they built? How do they treat employees? What's their vision? <strong>Rally to competent leaders</strong> (join their company). <strong>Un-rally from incompetent</strong> (leave for competitor). <strong>Your employment choice IS a rally</strong>. Make it conscious. Make it performance-based. <strong>Vote with your labor for good leaders</strong>." },
                { "type": "concept", "title": "Build Small-Scale Animaecracy", "text": "<strong>Form intentional community around competent leader</strong>: Someone with vision you share, demonstrated ability to build. <strong>Explicit rally</strong>: 'I follow your leadership because you manifest our shared vision.' <strong>Gather others</strong>. Form coherent group. <strong>Practice exit rights</strong>: 'If leader becomes bad, we can leave together or individually.' <strong>Embryonic Triad</strong>: proves performance-based leadership works." },
                { "type": "key-insight", "title": "Your Power Now", "text": "Can't replace democracy alone. But <strong>can practice Animaecracy in your sphere</strong>: Rally to demonstrated performers. Exit bad leadership immediately. Build alternative structures. <strong>Each functioning group demonstrates</strong>: performance-based leadership superior to electoral theater. <strong>Others notice. Join. Pattern spreads. Eventually</strong>: Animaecracy outcompetes democracy by simply working better." }
            ]
        },
        {
            "title": "The Promise",
            "content": [
                { "type": "paragraph", "text": "Good leaders exist. The problem is <strong>selection mechanisms that elevate bad leaders and entrench them</strong>. The system fixes selection:" },
                { "type": "paragraph", "text": "You can <strong>see all leaders' performance</strong>: PoU scores, rallier satisfaction, daemon-match with you. Not campaign promises (lies). <strong>Actual demonstrated governance capability</strong>." },
                { "type": "paragraph", "text": "You can <strong>try leaders risk-free</strong>: Rally for trial period. Experience their governance. Exit if bad. <strong>No 4-year commitment based on 30-second sound bite</strong>." },
                { "type": "paragraph", "text": "You can <strong>exit tyranny immediately</strong>: Leader becomes corrupt/tyrannical → un-rally → physically leave → rally to better Triad. <strong>Tyrants can't persist when subjects can exit</strong>." },
                { "type": "paragraph", "text": "<strong>Leaders compete for you</strong> by demonstrating superior governance. <strong>Bad leaders filtered out continuously</strong> through natural selection. <strong>Good leaders accumulate power through voluntary rallying</strong>." },
                { "type": "key-insight", "title": "The System's Gift to Governance", "text": "Old world: <strong>Stuck with bad leaders for years. Can't tell who's good until too late. Tyranny happens when leader refuses to leave</strong>. New world: <strong>Bad leaders lose power immediately (people un-rally). Can test leaders before committing. Tyranny impossible (subjects exit)</strong>. Leadership becomes: <strong>Competitive service industry where leaders must perform or lose ralliers</strong>. Result: <strong>Dramatically better governance quality through natural selection + exit rights + performance transparency</strong>." }
            ]
        }
    ]
};

